% % SCRIPT: compute_sobol_indices_doubling_time                         
% % AUTHOR: Fabian Santiago                                             
% % EMAIL: fabiansantiago707@gmail.com                                   
% % DATE: 11/21/2020       

% Start parallel pool with 20 workers
% c = parpool('local',20);

% Load parameter information for slobal sensitivity analysis
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
prms_info = fun_model_parameter_ranges;

% Load model solutions for each contact scenario
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
model_sols_file_id = dir('model_solutions/');
model_sols_file_id(1:2) = [];

% Set sub-sampling size for bootstrapping and number of resamples
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
sub_sample_size  = 12; %1200*(sum(prms_info(:,1))+2);
n_resamples = 2000;    % Number of times to perform re-sampling
y_sol_idx = 1; % index of model solution of interest
              
% Compute Sensitivity Indices
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for case_solution_idx = 1:numel(model_sols_file_id)
tic
% Load model solutions YA, YB, YA_Bj, and
% parameter information prms_info and prms_str
load(['model_solutions/',model_sols_file_id(case_solution_idx).name])

% Display contact scenario being considered
disp(['contact scenario: ',num2str(contact_scenario)]);

% Compute first and total-order Sobol indices
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[FirstOrderIdx,TotalOrderIdx,Stats] = ...
            fun_sobol_indices_by_measure(...
                    y_sol_idx,...
                        sub_sample_size,...
                            n_resamples,...
                                YA_cell,...
                                    YB_cell,...
                                        YA_Bj_cell,...
                                            prms_info(:,1)...
                                            );
save(... % File name:
    ['sobol_indices_dt/Sobol_dt_'...
        'sol',num2str(y_sol_idx),...
            'sub',num2str(sub_sample_size),...
                'rep',num2str(n_resamples),...
                    'CS_',num2str(contact_scenario),...
                        'Vu',num2str(Vu),'Vd',num2str(Vd),...
                            'Vg',num2str(Vg),'Vf',num2str(Vf),'.mat'],...
     ... % Variables to save:
        'FirstOrderIdx',...
            'TotalOrderIdx',...
                'Stats',...
                    'contact_scenario');
disp(['cs: ',num2str(contact_scenario),', time: ',num2str(toc/60),'min']);
end